### ISSUE TITLE
Supply control CSF mask to ravel-normalize

### ISSUE THREAD

**Issue by jimcost** [jcreinhold/intensity-normalization#10]
I'd like to normalize gad-enhanced T1ws. I can create the control CSF mask elsewhere. Is it feasible to add another input field to supply the control mask to `ravel-normalize`?

**Comment by jcreinhold** [comment]
I can add that, but I've never actually tried to `ravel-normalize` gad-enhanced T1-w images. Could you try it as is and add `-p` to the list of command line arguments. Then could you post the resulting histogram?

**Comment by jimcost** [comment]
Working on it, I'll get back to you by Friday.

**Comment by jimcost** [comment]
Post T1 histogram:

![postt1-ravel-hist](https://user-images.githubusercontent.com/6710629/57169019-b38d2c00-6dc1-11e9-8c2e-cf948c278193.png)

**Comment by jcreinhold** [comment]
Thanks for trying, I'll add a fix for this.

**Comment by jcreinhold** [comment]
Just as an update, I'll get to this next week. This week has been, and early next week is, a bit busy

**Comment by jcreinhold** [comment]
Sorry for the long delay. I provided a limited solution to the problem. 

You can supply your own control masks now by setting the `--csf-masks` flag when calling `ravel-normalize`. However, unlike the routine where CSF (i.e., control masks) are _not_ provided, you will have to deformably co-register the set of images yourself. Note that the CSF masks should correspond to these deformably co-registered images, not the original ones.

FWIW, there is a `coregister` command line interface provided in the package as well as a `tissue_mask` script which can provide CSF masks.

Please let me know if you run into any problems or have any questions about usage (if this wasn't delivered too late).
