### ISSUE TITLE
antspy need to be installed separately use --user in pip3 install if you don't have sudo authority

### ISSUE THREAD

**Issue by zzz123xyz** [jcreinhold/intensity-normalization#13]
antspy need to be installed separately use --user in pip3 install if you don't have sudo authority.

I have installed several times using the --antspy and --1.4, but unsuccessful. I finally use --user to solve this. 

another problem is an error occurs 
intensity_normalization.exec.preprocess - ERROR - unsupported pixeltype short

I install new version of antspy, problem solved :) 

really struggle to install this today.

**Comment by jcreinhold** [comment]
The antspy installation is going to be a problematic component because it generally requires the user build it from source. That is why antspy is only required for use with the RAVEL intensity normalization scheme.

Is there a specific issue with the package I should address?

**Comment by jcreinhold** [comment]
Please re-open if you continue to have a problem.
