### ISSUE TITLE
How to create the WM mask

### ISSUE THREAD

**Issue by zzz123xyz** [jcreinhold/intensity-normalization#14]
Hi Jacob
I have read the tutorial you write, I still cannot figure out how to create the WM mask. Supposed I have the T1-w images in my folder (t1_imgs/).  I create an empty folder for WM (brain_masks/) and an empty folder (out/) for normalized output. 
when I run:
`fcm-normalize -i t1_imgs/ -m brain_masks/ -o out/ -v -c t1`
I always run into error as:

```
Traceback (most recent call last):
.....
FileNotFoundError: [Errno 2] No such file or directory: 'brain_masks/'
```
Could you tell me how to deal with this. I have the T1-w files and want to use this tool to create the WM mask and normalize my T1-w images ?!

I follow the tutorial as follow:
> We use the T1-w image to create a mask of the WM over which we calculate the mean and normalize as previously stated (see here for more detail). This mask can then be used to normalize the remaining contrasts in the set of images for a specific patient assuming that the remaining contrast images are registered to the T1-w image.
Since all the command line interfaces (CLIs) are installed along with the package, we can run fcm-normalize in the terminal to normalize a T1-w image and create a WM mask by running the following command (replacing paths as necessary):

`fcm-normalize -i t1_w_image_path.nii.gz -m mask_path.nii.gz -o t1_norm_path.nii.gz -v -c t1 -s`

> This will output the normalized T1-w image to t1_norm_path.nii.gz and will create a directory called wm_masks in which the WM mask will be saved. You can then input the WM mask back in to the program to normalize an image of a different contrast, e.g. for T2,

**Comment by jcreinhold** [comment]
That part of the tutorial isn't very clear; I updated the tutorial for clarification. The `brain_masks` directory is a directory of brain masks, not a directory to hold the output WM masks. 

So you first need to create brain masks for the (non-gadolinium enhanced) T1-w images. The brain masks do not need to be perfect. You can use [ROBEX](https://sites.google.com/site/jeiglesias/ROBEX), as an example, to create the brain masks.

See the tutorial for updated information and how to proceed. In the future, if you use `fcm-normalize -h` you can get more information about the arguments and what they expect as input.
