### ISSUE TITLE
Is that possible to record the transformation in the co-registration function ?

### ISSUE THREAD

**Issue by zzz123xyz** [jcreinhold/intensity-normalization#15]
Hi Jacob
    Here, I want to apply the co-registration operation to the corresponding label masks of my data of head images. I have used the co-registration operation to transformed all my sample images to the 'NMI' template, my goal is to do the same transformation on all my corresponding label masks of my data. I don't know if it is possible to do like that in this intensity-normalization tool. 
    Thanks
Lance

**Comment by jcreinhold** [comment]
For this application, I wouldn't use the `coregister` tool provided in this package. The `coregister` tool is just a wrapper for ANTs, so I would just use ANTs for this purpose so that you can save the transforms and apply them yourself to other datasets.

Best of luck.

**Comment by zzz123xyz** [comment]
Thanks for the information
