### ISSUE TITLE
Incorrect coregister for label mri

### ISSUE THREAD

**Issue by LarisaKozhekina** [jcreinhold/intensity-normalization#19]
## 🐛 Bug

I am trying to make coregister to my dataset and use one of BRATS19 image as template. All images registered right but when i tried to register label with it i got it wrong. I think that label after coregister is not right or higher(shift for z axis) than mri image.

## To Reproduce

1. I cloned your project from github 
2. I updated coregister function due to different directories structure. See code in attachment
[coregister.txt](https://github.com/jcreinhold/intensity-normalization/files/4421665/coregister.txt)
3.Input data: for template BraTS19_2013_1_1 https://drive.google.com/drive/folders/15wsRop7Ha_WCU579oWQ3mYkKpvvFh96o?usp=sharing
for my dataset mts3 image https://drive.google.com/file/d/1jk8C57mOeyrgmkJwgQ6kWKhvIin3ugqT/view?usp=sharing and label https://drive.google.com/file/d/16NhkMolL4ai0V2wOJvKfsCh6SMS3XNg7/view?usp=sharing

## Expected behavior
Before coregister: label matches tumor on image.
![3](https://user-images.githubusercontent.com/16781515/78262230-f216f380-7508-11ea-898e-2b8191519713.PNG)

Images after coregister in MITK Workbench:
red is label and for 1 it is too smal. for 2 there must be no red.
![1](https://user-images.githubusercontent.com/16781515/78261651-28a03e80-7508-11ea-90b3-5fc0a586b29d.PNG)
![2](https://user-images.githubusercontent.com/16781515/78261667-2b9b2f00-7508-11ea-90d9-b72ac885d240.PNG)

## Environment
 - I don't see any version for intensity-normalization but it is last version from github and coregister function was created on Jun 19, 2018.
 - numpy version 1.18.2.
 - Google Colaboratory.
 - Installed intensity-normalization by git clone.
 - copied and call fuction coregister
 - Python 3.6.9:
 - Ants from pip install antspyx '0.2.5'

**Comment by jcreinhold** [comment]
Thanks for following the form and thanks for the feedback. Two problems:

1. The `coregister` script is a convenience script that simply calls ANTs assuming a specific directory structure. If your directory structure differs from the one specified in my `coregister` script, the intent of the `coregister` script is that you will modify the directory structure to fit what the `coregister` script expects. If doing that is too cumbersome, just use ANTs by itself. You'll have more control over the process and know exactly what is going on. Unfortunately, I do not have the time to support user-modified scripts.
2. You can't register a label image to a structural image without an intermediate step. To register a label image you need to register the image that the label was drawn on to the template image. Then you can use that same transform on the label image. You can do this in the`coregister` script; the `coregister` script saves the transforms in the output directory under `tfms`. So if you first register the structural image that the label was drawn on to the template, you can then use the created transforms as input to the `coregister` script in the `--tfm-dir` option with the labels as the `--img-dir` (make sure you use the option `-itp nearestNeighbor`). 

If you are already doing what I've described in the second point, then I would recommend using ANTs or ANTsPy by itself. Those packages are great and better suited for the tasks you are trying to do.

If you use the `coregister` script, unmodified, as described in the second point, and you still run into a problem, please re-open this issue and I can try to help.
