### ISSUE TITLE
No documentation for brain_mask in intensity_normalization.normalize.fcm.find_tissue_mask

### ISSUE THREAD

**Issue by goyal-aman** [jcreinhold/intensity-normalization#26]
## 📚 Documentation

To normalize the T1 Weighted image, using normalize **normalize.fcm.fcm_normalize** which require **tissue_mask** for which according to documentation I am using this **normalize.fcm.find_tissue_mask** in which **brain_mask** is a required parameter but there is no refrence in documentation that I can find about what it should be.

**Comment by jcreinhold** [comment]
Hi @goyal-aman. I'm not sure I understand. There is documentation about what the `brain_mask` argument should be in the docstring. See [here](https://github.com/jcreinhold/intensity-normalization/blob/bd51bb6b467cbb937e43393f306d17af471d09f4/intensity_normalization/normalize/fcm.py#L57).

Can you clarify what you mean?

**Comment by goyal-aman** [comment]
Hi @jcreinhold,  sorry for not being clear. What I meant was I couldn't find anywhere in the documentation that what should be passed in the brain_mask argument. I am just getting started with brain_image processing. I apologise is question sound dumb.

**Comment by jcreinhold** [comment]
@goyal-aman No problem. My documentation isn't clear—you're question is good. The brain mask should be a binary array, the same size as the MR/CT image, which is 1 in the voxels/pixels corresponding to the brain and 0 in all other voxels/pixels.

Hope that helps. I am going to close this and factor this into my open issue regarding refactoring the package (#24).
