### ISSUE TITLE
make `brain_mask` argument optional

### ISSUE THREAD

**Issue by function2-llx** [jcreinhold/intensity-normalization#30]
## 🚀 Feature
make `brain_mask` argument optional in some commands, e.g. `fcm-normalize`

## Motivation
I've got some partially processed images which are skull-stripped, and I'd like to conduct intensity normalization on them now. Because it's already skull-stripped I think it's reasonable to input solely this image to the program without specifying any brain mask. However the `fcm-normalize` does not let me do so, complaining I must specify one mask [here](https://github.com/jcreinhold/intensity-normalization/blob/5f2fc9ea3f305a3bd214b6f42fd8b1664a3ecbdc/intensity_normalization/exec/fcm_normalize.py#L85) (BTW if the message here was "One and only one mask should be specified", it would be more precise because operation here is xor). 

There should be a simple workaround that I could create a mask covering the whole brain (has "1" everywhere) somewhere on my filesystem, but I think we can make it more elegant by making this argument optional.

## Pitch
Make `brain_mask` optional with the default value of the whole brain's mask.

## Alternatives
Add a new argument for explicitly informing that the image was already skull-stripped.

**Comment by jcreinhold** [comment]
Thanks for this. You're right that it should be optional for skull-stripped images. I'm in the process of refactoring the code, so I'll incorporate this into the update.

**Comment by jcreinhold** [comment]
brain masks are now optional in v2.0.0 (ede16c34212eed04f625c527fd9358a40142a08f)
