### ISSUE TITLE
Add a conda recipe

### ISSUE THREAD

**Issue by sarthakpati** [jcreinhold/intensity-normalization#31]
## 🚀 Feature

Thanks for the great work! It would be really nice if this were available via conda-forge, as well.

## Motivation

Integrating with other packages that need conda-specific libraries would be easier.

## Pitch

I have a reasonable amount of experience dealing with conda recipes, so I can take care of it.

## Alternatives

N.A.

## Additional context

Already working on the recipe: https://github.com/conda-forge/staged-recipes/pull/15441

**Comment by sarthakpati** [comment]
BTW, I am more than happy to add anyone else as maintainer for that recipe. conda recipes automatically update themselves with every push to pip, so there is minimal overhead.

**Comment by jcreinhold** [comment]
A conda recipe would be great! Thanks for this. Definitely happy for the contribution. Just FYI, I am in the process of a major refactor (see https://github.com/jcreinhold/intensity-normalization/tree/refactor). Let me know if you need any information/help from me.

**Comment by sarthakpati** [comment]
Sounds good. Don't think I would need anything from you at this point. Do you have a timeline on when you will be merging the refactor upstream and pushing a new pip build out?

**Comment by jcreinhold** [comment]
I just moved to a different city so the refactor was put on hold, but I should be able to get around to it by the end of the week.

**Comment by sarthakpati** [comment]
Oh okay. Was asking because it would be great if I can wrap up the conda recipe first, so that all subsequent builds will get picked up automatically. 😄
