### ISSUE TITLE
Output and input distribution file in Sample-based normalization methods

### ISSUE THREAD

**Issue by wjtan99** [jcreinhold/intensity-normalization#36]
## 🚀 Feature
Output density distribution from a set of images into a file, then read this file back in for different sets of images 

## Motivation
It is very common that we work with different sets of images. For example, in deep learning, we have the training, validation, and testing sets.  We can use a sample-based normalization method to find the average density distribution, and normalize the images to this distribution.  But how can we normalize the validation and testing sets to this same distribution? An easy way is we output the distribution of the training sets and save it into a file. Then we read this file back in to do the normalization on the validation and testing sets, without having to mixing the images in the validation and testing sets with the images in the training sets. 

## Pitch

We output the distribution of the training sets and save it into a file. Then we read this file back in to do the normalization on a different set.

**Comment by jcreinhold** [comment]
I added support for this for Nyul and LSQ. Re-install the package. Make sure your version is v2.0.1.

Fitting and using for arbitrary images is supported in the Python API. For example, you can run:

```python
# load images
import nibabel as nib
image_paths = ["path/to/image1.nii", "path/to/image2.nii", ...]
images = [nib.load(image_path) for image_path in image_paths]

# normalize the images and save the standard histogram
from intensity_normalization.normalize.nyul import NyulNormalize
nyul_normalizer = NyulNormalize()
nyul_normalizer.fit(images)
normalized = [nyul_normalizer(image) for image in images]
nyul_normalizer.save_standard_histogram("standard_histogram.npy")

# load new images and normalize those
new_image_paths = ["path/to/another/image1.nii", "path/to/another/image2.nii", ...]
new_images = [nib.load(image_path) for image_path in new_image_paths]
normalized = [nyul_normalizer(image) for image in images]

# load the standard histogram
new_nyul_normalizer = NyulNormalize()
new_nyul_normalizer.load_standard_scale("standard_histogram.npy")
normalized = [new_nyul_normalizer(image) for image in images]
```

For LSQ:

```python
from intensity_normalization.normalize.lsq import LSQNormalize
lsq_normalizer = LSQNormalize()
lsq_normalizer.fit(images)
normalized = [lsq_normalizer(image) for image in images]
lsq_normalizer.save_standard_tissue_means("tissue_means.npy")

# reload the tissue means and use
lsq_normalizer = LSQNormalize()
lsq_normalizer.load_standard_tissue_means(tissue_means.npy")
normalized = [lsq_normalizer(image) for image in images]
```

RAVEL is only meant to work on a particular batch, so you need to refit it if you add new data to your batch or want to use it to normalize new data.

Similar options are added to the CLI. For `nyul-normalize` the relevant new options are `--save-standard-histogram` and `--load-standard-histogram`. For LSQ, `--save-standard-tissue-means` and `--load-standard-tissue-means`.

Let me know if you run into a bug. Reopen the issue if so.

**Comment by wjtan99** [comment]
Thanks a lot for your quick response.
