### ISSUE TITLE
Njul histogram matching

### ISSUE THREAD

**Issue by MLRadfys** [jcreinhold/intensity-normalization#38]
## 📚 Documentation

Hi and thanks for sharing your code!
Maybe the documentation section is not the right place for my post, bu I'll give it a try :-)

There is an implementation of Njus normalization algorithm  in ITK / SimpleITK that lets one perform histogram matching between a source image and a template image (HistogramMatchingFilter).

Would this be possible using your implementation as well?

Thanks in advance,

kind regards,

M

**Comment by jcreinhold** [comment]
The Nyul & Udupa (piecewise affine) histogram matching method is implemented in this package:

**Comment by MLRadfys** [comment]
Thanks for your quick reply!

I will read through the docs and come back to you.

Cheers,

M
