### ISSUE TITLE
Nyul normalize not working with custom output range

### ISSUE THREAD

**Issue by MLRadfys** [jcreinhold/intensity-normalization#39]
## 🐛 Bug

Hi Jacob.

**My post is more a question about the functionality of your code and not a bug!**

Iam trying to use your implementation of Nyuls intensity nromalziation algorithm to match histograms between computed tomography (CT) images and synthetic CT images (even though Iam aware of that it is written for MRI images). 
ITK has an implementation of Nyul's algorithm, were it is possible to match the histogram between a source image and a template image, where the CDF of the source image is matched against the CDF of the template image.
The matched image is returned having the same range as the template image (-1000, 3096 for a 12-bit CT image).

The ITK version works fine, though I want to use several template images to compute the standard histogram, which does not seem to be possible.

When I run my images through your code, the output image has a totally different range, which I guess depends on how you set (defaultvalues between 0-100). 
The images used to compute the standard histogram all have the same range (-1000, 3096) in my case.
Nevertheless, when I set the range to -1000 , 3096 the max values of the output image are only at around 300.

So my question is, how can I maintain the range when fitting my input images and how can I normalize a new image so that is is returned in the same range as the fitted ones?

Thanks in advance,

kind regards,

M

## Expected behavior

I expected the matched images the range pecified, in example if fitted with -1000 - 3096, all normalized images should be in that range.

## Environment

 - intensity-normalization version (e.g., 0.3.8): latest
 - numpy version (e.g., 1.0): 1.19.3
 - OS (e.g., Linux): Windows
 - How you installed intensity-normalization (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): ---
 - Python version: 3.9.0
 - Any other relevant information: ---

**Comment by jcreinhold** [comment]
Thanks for the feedback. Can you provide your python code?

**Comment by jcreinhold** [comment]
I suspect you're using the wrong arguments. I updated the package to improve the names of the parameters. See [here](https://intensity-normalization.readthedocs.io/en/latest/intensity_normalization.normalize.html#module-intensity_normalization.normalize.nyul) for a description of the parameters. 

I just tested the package changing `output_min_value` and `output_max_value` to -2000 and 2000, respectively, and it worked. Please reinstall the package and use the updated parameters and reopen/comment on this issue if you still have a problem.

**Comment by jcreinhold** [comment]
Related #37

**Comment by MLRadfys** [comment]
Hi and thanks again for all help.

I now tried the latest version which gives me the negative value warning.

I will try to input a mask as well and get back to you asap.

Cheers,

M
