### ISSUE TITLE
Allow images of different sizes in RAVEL

### ISSUE THREAD

**Issue by jcreinhold** [jcreinhold/intensity-normalization#4]
The RAVEL normalization method requires all images have the same dimension. Allow users to use a directory of various image dimensions.

Reference #3.

**Comment by jcreinhold** [comment]
I am not going to get around to this, closing this with wontfix. If enough people (>=2) bring this up again as a want, then I will try to get around to it.

**Comment by Yingping-LI** [comment]
Thanks a lot if you could help to solve this problem.

Have a nice day: )

**Comment by jcreinhold** [comment]
Hi @Yingping-LI , unfortunately I've been pretty busy lately, so it's unlikely I'll be able to get to this soon. The way that RAVEL works makes this a non-trivial fix (if I'm recalling how it works correctly). If you want to use RAVEL anytime soon, I'd suggest registering all the images to a common space (e.g., MNI)—making sure the images are all of the same dimension on the output—and then using this method. Hope this helps.

**Comment by Yingping-LI** [comment]
Hi @jcreinhold, thanks a lot for your quick reply and the explanation of the optional solution.
I will try your suggested method, thanks! Have a nice day: )
