### ISSUE TITLE
Add/check Python v3.10 support

### ISSUE THREAD

**Issue by jcreinhold** [jcreinhold/intensity-normalization#42]
## 🚀 Feature
intensity-normalization should support Python >=v3.10

**Comment by pooya-mohammadi** [comment]
Do you have any plans for supporting python >=3.10?

**Comment by jcreinhold** [comment]
At some point I'd like to. I'm not sure when I'll get time to update the code though. I'd be happy to review and accept a suitable PR!

**Comment by jcreinhold** [comment]
Fixed with 5853a339021a57f53da154276bbec92e665d7fe8
