### ISSUE TITLE
Using normalization methods -- bash

### ISSUE THREAD

**Issue by johnpp4** [jcreinhold/intensity-normalization#80]
## To Reproduce

1. Following installation guide.
2. Going to a python environment in shell
3. Running 'from intensity_normalization.normalize.fcm import FCMNormalize'.

```
  File "../../intensity-normalization/intensity_normalization/typing.py", line 46, in <module>
    ArgType = typing.Union[argparse.Namespace, list[str], None]
TypeError: 'type' object is not subscriptable
```

## Expected behavior
running the normalization method on images.

## Environment

 - intensity-normalization version (e.g., 0.3.8): yes
 - numpy version (e.g., 1.0): yes
 - OS (e.g., Linux): yes
 - How you installed intensity-normalization (`conda`, `pip`, source): pip
 - Build command you used (if installed from source): 
 - Python version: 3.8.10
 - Any other relevant information:

**Comment by jcreinhold** [comment]
You're receiving this error because you're using Python v3.8. Python >=3.9 is required to use this package.
